# Generated by Django 4.0 on 2022-05-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_crudst'),
    ]

    operations = [
        migrations.CreateModel(
            name='crudst1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=200)),
                ('dversion', models.IntegerField()),
                ('nameofcustomer', models.CharField(max_length=150)),
                ('customermobileno', models.IntegerField()),
                ('dateofselling', models.DateField()),
            ],
        ),
    ]
