# Generated by Django 4.0 on 2022-06-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_crudst1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('milktype', models.CharField(blank=True, max_length=50)),
                ('fat', models.FloatField(max_length=10)),
                ('snf', models.FloatField(max_length=10)),
                ('clr', models.FloatField(max_length=10)),
                ('water', models.FloatField(max_length=10)),
                ('temp', models.FloatField(max_length=10)),
                ('weight', models.FloatField(max_length=10)),
                ('price', models.FloatField(max_length=10)),
                ('time', models.TimeField()),
            ],
        ),
    ]
